<?php

$_start_date = $block->getData('start_date');
$_end_date = $block->getData('end_date');

$_report = $block->getData('report');
$report_type = "day";

if (count($_report) > 0) {
    ?>
    <div style="font-size: 11px; overflow-x: auto;">
        <table border="0" cellspacing="0" cellpadding="2">
            <tr>
                <td valign="top">
                    <table border="0" cellspacing="2" cellpadding="2">
                        <tr class="dataTableHeadingRow">
                            <td align="center" width="160"
                                style="background-color: white; font-family: Verdana,Arial,sans-serif; font-size: 10px; color: rgb(255, 255, 255); font-weight: bold;">
                                &nbsp;</td>
                            <?php
                            foreach (array_keys($_report) as $admin_name) {
                                ?>
                                <td align="center"
                                    style="  font-family: Verdana,Arial,sans-serif; color: rgb(255, 255, 255); font-weight: bold; font-size: 12px; width: 250px;">
                                    <table width="95%" border="0">
                                        <tr>
                                            <td style="text-align: center;">
                                                <?php echo $admin_name; ?>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <?php
                            }
                            ?>
                        </tr>

                        <?php
                        while (1) {
                            if (isset($_report_end_date)) {
                                if ($report_type == "week" || $report_type == "month" || $report_type == "year") {
                                    $_report_start_date = mktime(0, 0, 0,
                                        date("m", $_report_end_date),
                                        date("d", $_report_end_date) + 1,
                                        date("Y", $_report_end_date));
                                } else {
                                    $_report_start_date = $_report_end_date;

                                    $_report_start_date = mktime(0, 0, 0,
                                        date("m", $_report_end_date),
                                        date("d", $_report_end_date) + 1,
                                        date("Y", $_report_end_date));
                                }
                            } else {
                                $_report_start_date = strtotime($block->getDate(null,
                                    strtotime($_start_date)));
                            }

                            if ($_report_start_date > strtotime($block->getDate(null,
                                    strtotime($_end_date)))
                            ) {
                                break;
                            }

                            // calculate end date
                            $_report_end_date = mktime(23, 59, 59,
                                date("m", $_report_start_date),
                                date("d", $_report_start_date),
                                date("Y", $_report_start_date));

                            // make date label
                            $_report_date_label = date('m/d/Y',
                                $_report_start_date);

                            ?>
                            <tr style="background-color: #DADFE0;">
                                <td style="font-family: Verdana,Arial,sans-serif; font-size: 11px; color: rgb(0, 0, 0);"
                                    align="center"
                                    width="160"><?php echo $_report_date_label; ?></td>
                                <?php
                                $currency_symbol = $block->getCurrencySymbol();

                                $subtotals = [];

                                foreach ($_report as $admin_name => $admin_data) {
                                ?>
                                <td style="font-family: Verdana,Arial,sans-serif; font-size: 11px; color: rgb(0, 0, 0);"
                                    align="center" valign="top"
                                    style="width: 250px;">
                                    <table width="95%" border="0">
                                        <?php
                                        $_has_orders = false;

                                        foreach ($admin_data['orders'] as $_order) {
                                            if (strtotime($_order['created_at']) > $_report_start_date && strtotime($_order['created_at']) < $_report_end_date) {
                                                if ($_order['show_status'] && "No Sales Rep." != $admin_name) {
                                                    if ($_order['status'] != "") {
                                                        $_salesrep_icon = $block->getViewFileUrl('Cminds_Salesrep::images/salesrep/' . strtolower($_order['status']) . '.png',
                                                            ['_area' => 'adminhtml']);
                                                    } else {
                                                        $_salesrep_icon = $block->getViewFileUrl('Cminds_Salesrep::images/salesrep/unpaid.png',
                                                            ['_area' => 'adminhtml']);
                                                    }
                                                    echo '<td style="width: 16px;"><img style="margin-top: 2px;" src="' . $_salesrep_icon . '" alt="' . $_order['status'] . ' icon" title="' . $_order['status'] . '" /></td>';
                                                }

                                                if ("No Sales Rep." != $admin_name) {
                                                    echo '<td align="left">';
                                                } else {
                                                    echo '<td align="center">';
                                                }

                                                echo '<a style="vertical-align: top;" target="_blank" href="' . $block->getUrl('sales/order/view',
                                                        ['order_id' => $_order['order_id']]) . '">';
                                                echo $_order['order_increment_id'];

                                                if ($_order['is_manager']) {
                                                    echo ' (M)';
                                                }

                                                echo '</a>';
                                                echo "({$_order['order_status']})";
                                                echo '</td>';

                                                if ("No Sales Rep." != $admin_name) {
                                                    echo '<td align="right">';

                                                    echo $_order['value'] != '' ? $block->getCurrency($_order['value']) : '';

                                                    echo '</td>';
                                                    echo '</tr>';
                                                }


                                                // Calc subtotal earned for period
                                                if (isset($subtotals[$admin_name])) {
                                                    $subtotals[$admin_name]['subtotal'] += round($_order['value'],
                                                        2);
                                                    $subtotals[$admin_name]['orders'] += 1;
                                                } else {
                                                    $subtotals[$admin_name] = [
                                                        'subtotal' => round($_order['value'],
                                                            2),
                                                        'orders' => 1
                                                    ];
                                                }

                                                $_has_orders = true;
                                            }
                                        }

                                        if (!$_has_orders) {
                                            $subtotals[$admin_name] = [
                                                'subtotal' => 0,
                                                'orders' => 0
                                            ];

                                            echo '<tr><td colspan="2" align="center">-</td></tr>';
                                        }
                                        ?>
                                    </table>
                                    <?php
                                    }
                                    ?>
                                </td>
                            </tr>
                            <tr style="background-color: #fcf5dd; cursor: pointer;">
                                <td style="font-family: Verdana,Arial,sans-serif; font-size: 11px; color: rgb(0, 0, 0);">
                                    &nbsp;</td>
                                <?php
                                foreach (array_keys($_report) as $admin_name) {
                                    ?>
                                    <td style="font-family: Verdana,Arial,sans-serif; font-size: 11px; color: rgb(0, 0, 0);"
                                        align="center" valign="top">
                                        <?php
                                        if ("No Sales Rep." != $admin_name) {
                                            ?>
                                            <table style="width: 95%;"
                                                   border="0">
                                                <tr>
                                                    <td style="width: 16px;"></td>
                                                    <td align="left">
                                                        <b>Orders: </b><?php echo $subtotals[$admin_name]['orders']; ?>
                                                    </td>
                                                    <td align="right">
                                                        <?php if ($_report[$admin_name]['show_comm']) { ?>
                                                            <b>Subtotal:</b> <?php echo $subtotals[$admin_name]['subtotal'] == '' ? $block->getCurrency(0) : $block->getCurrency($subtotals[$admin_name]['subtotal']) ?>
                                                        <?php } ?>
                                                    </td>
                                                </tr>
                                            </table>
                                            <?php
                                        }
                                        ?>
                                    </td>
                                    <?php
                                }
                                ?>
                            </tr>
                            <?php
                        }
                        ?>

                        <tr>
                            <td width="160">&nbsp;</td>
                            <?php
                            foreach (array_keys($_report) as $admin_name) {
                                ?>

                                <td style="width: 250px; font-family: Verdana,Arial,sans-serif; font-size: 11px; color: rgb(0, 0, 0); text-align: center;">
                                    <table
                                        style="width: 90%; margin: 10px; font-size: 15px; font-weight: bold;">
                                        <?php
                                        if ("No Sales Rep." != $admin_name && $_report[$admin_name]['show_comm']) {
                                            ?>
                                            <tr>
                                                <td>Paid Total:</td>
                                                <td style="color: green; font-size: 15px; font-weight: bold; margin: 10px; text-align: right;"><?php echo $block->getCurrency($_report[$admin_name]['paid_total']); ?></td>
                                            </tr>
                                            <tr>
                                                <td>Unpaid Total:</td>
                                                <td style="color: red; font-size: 15px; font-weight: bold; margin: 10px; text-align: right;"><?php echo $block->getCurrency($_report[$admin_name]['unpaid_total']); ?></td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                    </table>
                                </td>
                                <?php
                            }
                            ?>
                        </tr>
                    </table>

                </td>
            </tr>
        </table>
    </div>
    <?php
} else {
    ?>
    No report available.
    <?php
}
?>
