<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_SecurityAuth
 */
?>
<?php
/** @var \Amasty\SecurityAuth\Helper\Data $_helper */
$_helper = $this->helper('Amasty\SecurityAuth\Helper\Data');
?>

<?php if ($_helper->isActive()) : ?>
    <div class="admin__field field-username">
        <label for="username" class="admin__field-label">
            <span><?php /* @escapeNotVerified */ echo __('Security Code') ?></span>
        </label>
        <div class="admin__field-control">
            <input id="<?php echo Amasty\SecurityAuth\Helper\Data::CODE_NAME_FOR_INPUT_FORM ?>"
                   class="admin__control-text"
                   type="text"
                   name="<?php echo Amasty\SecurityAuth\Helper\Data::CODE_NAME_FOR_INPUT_FORM ?>"
                   value=""
                   placeholder="<?php /* @escapeNotVerified */ echo __('Security Code') ?>"
                   autocomplete="off"
            />
        </div>
    </div>
<?php endif;?>