<?php if($block->isDisplayed()): ;?>
<div class="admin__page-section-title <?php  echo $block->escapeHtml($block->getHeaderCssClass()) ?>">
    <span class="title">
        <?php echo $block->escapeHtml($block->getHeaderText()) ?>
    </span>
    <div class="actions"></div>
</div>
<div id="customer_account_fieds" class="admin__page-section-content">
    <input id="base_url_salesrep" type="hidden" value="<?php echo $block->getBaseUrl();?>"/>
    <input id="salesrep_change_selectsalesrepadmin_url" type="hidden" value="<?php echo $this->getUrl('salesrep/order/Selectsalesrepadmin'); ?>"/>
    <label class="admin__field-label" style="margin-bottom: 15px;display: block;text-align: left;">
        <?php echo $block->escapeHtml($block->getSalesrepNote());?>
    </label>
    <?php
        $authSession= $block->getLayout()->createBlock('Cminds\Salesrep\Block\Adminhtml\Reports\Commissions\Grid');
        $currentAdminUser = $authSession->currentAdminUser();
        $getUserId = $currentAdminUser->getUserId();
    ?>
    <select id="sales_representative" class="select admin__control-select">
        <?php foreach($block->getSalesrepList() as $salesrep):?>
        <option value="<?php echo $block->escapeHtml($salesrep['value'])?>" <?php if($salesrep['value']
        == $getUserId) echo 'selected="selected"'; ?> >
            <?php echo $block->escapeHtml($salesrep['label'])?>
        </option>
        <?php endforeach;?>
    </select>
    </br>
    </br>
</div>

<script>
    require(["prototype", "Magento_Sales/order/create/form"], function(){
        order.accountFieldsBind($('customer_account_fieds'));
    });
</script>

<script type="text/javascript">
    require(['jquery'], function($){
        $(document).ready(function () {
            $('#sales_representative').trigger("change"); 
        });
    });
</script>
<?php endif;?>
