<?php
/** @var \Mirasvit\Rma\Block\Rma\NewRma\Step2 $block */
?>

<div data-mage-init='{"rmaNew": {}}'></div>
<div class="rma-new-step2">
    <form id="rma-new-form" action="<?= $block->getStep2PostUrl() ?>" method="POST" enctype="multipart/form-data"
          data-hasrequired="<?= __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>

        <?= $block->getChildHtml('rma.new.step2.info') ?>

        <?php if ($block->getAllowGift()): ?>
            <?= $block->getChildHtml('rma.new.gift') ?>
        <?php endif ?>

        <?= $block->getChildHtml('rma.new.step2.items') ?>
        <?= $block->getChildHtml('rma.new.step2.custom_fields') ?>
        <?= $block->getChildHtml('rma.new.step2.additional') ?>
        <?= $block->getChildHtml('rma.new.step2.policy') ?>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action primary" data-role="rma-submit">
                    <span><?= __('Submit Request') ?></span>
                </button>
            </div>
        </div>
    </form>

    <style type="text/css">
        #rma_remove_item1 {
            display: none;
        }
    </style>
    <div style="display:none" id="error_message_no_items">
        <?= __('Please, select RMA items which you would like to return.') ?>
    </div>
</div>