<?php
/**
 * Copyright © 2015 Collins Harper. All rights reserved.
 * See COPYING.txt for license details.
 */
return [
        'is_mock' => true,
        'shipping/origin/country_id' => 'CA',
        'shipping/origin/region_id' => '66',
        'dest_region_code' => 'AB',
        'shipping/origin/street_line1' => '123 Lameys Mill',
        'shipping/origin/city' => 'Didbury',
        'dest_postcode' => 'T0M 0W0',
        'shipping/origin/postcode' => 'T0M 0W0',
        'package_value' => '5',
        'package_value_with_discount' => '5',
        'package_weight' => '5',
        'package_qty' => '1',
        'package_physical_value' => '5',
        'free_method_weight' => '5',
        'store_id' => '1',
        'website_id' => '1',
        'free_shipping' => '0',
        'limit_carrier' => null,
        'base_subtotal_incl_tax' => '5',
        'orig_country_id' => 'CA',
        'country_id' => 'CA',
        'region_id' => '67',
        'city' => 'Vancouver',
        'postcode' => 'V6B 1R8',
    'carriers/cpcanadapost/methods' => 'DOM.EP,DOM.LIB,DOM.PC,DOM.RP,DOM.XP,DOM.XP.CERT,USA.EP,USA.PW.ENV,USA.PW.PAK,USA.PW.PARCEL,USA.SP.AIR,USA.TP,USA.TP.LVM,USA.XP,INT.IP.AIR,INT.IP.SURF,INT.PW.ENV,INT.PW.PAK,INT.PW.PARCEL,INT.SP.AIR,INT.SP.SURF,INT.TP,INT.XP',
    'carriers/cpcanadapost/allowed_methods' => 'DOM.EP,DOM.LIB,DOM.PC,DOM.RP,DOM.XP,DOM.XP.CERT,USA.EP,USA.PW.ENV,USA.PW.PAK,USA.PW.PARCEL,USA.SP.AIR,USA.TP,USA.TP.LVM,USA.XP,INT.IP.AIR,INT.IP.SURF,INT.PW.ENV,INT.PW.PAK,INT.PW.PARCEL,INT.SP.AIR,INT.SP.SURF,INT.TP,INT.XP',

        'girth' => null,
        'height' => null,
        'length' => null,
        'width' => null,
        'weight' => 1,
        'carriers/cpcanadapost/test' => true,
        'carriers/cpcanadapost/debug' => true,
        'carriers/cpcanadapost/cache' => 'false',
        'carriers/cpcanadapost/platform_id' => '0008004925',
        'carriers/cpcanadapost/platform_api_login' => '247a823a246b71c5',
        'carriers/cpcanadapost/platform_api_password' => 'ab347a8da40d5b57e8941e',
        'carriers/cpcanadapost/api_customer_number' => '2004381',
        'carriers/cpcanadapost/api_url' => 'https://soa-gw.canadapost.ca',
        'carriers/cpcanadapost/api_test_url' => 'https://ct.soa-gw.canadapost.ca',
        'carriers/cpcanadapost/contract' => '0042264519',
        'carriers/cpcanadapost/api_customer_number' => '0008004925',
        'carriers/cpcanadapost/api_test_login' => '59e8337d48c7fb8d',
        'carriers/cpcanadapost/api_test_password' => 'ea40b93238751b895c4966',
        'carriers/cpcanadapost/output_format' => '8.5x11',
        'carriers/cpcanadapost/require_coverage' => 'never',
        'rate_request_json' => '{"xmlns":"http:\/\/www.canadapost.ca\/ws\/ship\/rate","weight":0.002,"postal-code":"v6b 1r8","country_code":"CA","box":{"l":10,"w":10,"h":10,"weight":0.001},"coverage":0}',
        'all_items' => [],
];
