<?php
$block->cardData();
//$storeId = Mage::app()->getStore()->getId();
//$skip3d = Mage::getStoreConfig('payment/optimal_hosted/skip3D', $storeId);
//$allowInterac = Mage::getStoreConfig('payment/optimal_hosted/allow_interac', $storeId);
//$info = $this->getCardInfo();
//
//// if 3D-Secure check is enabled, only show the Payment Method Title
//if ((!$skip3d || $allowInterac) && empty($info['card_number'])) {
//    echo Mage::getStoreConfig('payment/optimal_hosted/title', $storeId);
//    return;
//}
//
