<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\StoreCredit\Block\Adminhtml\Sales\Order\Create\Payment */
?>
<?php if ($block->canShow()): ?>
    <div class="admin__field admin__field-option">
        <input id="p_method_aw_use_store_credit"
               class="admin__control-checkbox"
               name="payment[aw_use_store_credit]"
               type="checkbox"
               title="<?php echo $block->escapeHtml(__('Store Credit')) ?>"
               value="1"
            <?php /* @noEscape */ echo $block->isUseAwStoreCredit() ? 'checked="checked"' : '' ?> />
        <label class="admin__field-label" for="p_method_aw_use_store_credit">
            <?php /* @noEscape */ echo __('Use Store Credit (%1 available)', $block->formatPrice($block->getBalance())) ?>
        </label>
    </div>
    <script>
        require(['prototype'], function(){
            toggleUseAwStoreCredit = function()
            {
                var data = {};

                data['payment[aw_use_store_credit]'] = ($('p_method_aw_use_store_credit').checked ? 1 : 0);
                order.loadArea(['totals', 'billing_method'], true, data);
            }
            Event.observe($('p_method_aw_use_store_credit'), 'change', toggleUseAwStoreCredit);
            Event.observe(window, 'load', toggleUseAwStoreCredit);
        });
    </script>
<?php endif; ?>
