<?php
/** @var \Cminds\Salesrep\Block\Adminhtml\Reports\Commissions\Grid $block */
$data = [];

if (!empty($block->getFilterData()->getData())) :
    $tmpData = $block->prepareReportData();
    $data = $block->sortReportData($tmpData);

    $reportType = $block->getFilterData()->getPeriodType();
    $from_date = $block->getFilterDate(
        strtotime(
            $block->getFilterData()->getFrom() . ' 00:00:00'
        )
    );
    $to_date = $block->getFilterDate(
        strtotime(
            $block->getFilterData()->getTo() . ' 00:00:00'
        )
    );
    if (count($data) > 0) :
        ?>
        <style>
            .dataTableHeadingRow {
                background-color: #5F767F;
            }

            .dataTableHeadingContent {
                font-family: Verdana, Arial, sans-serif;
                font-size: 10px;
                color: rgb(255, 255, 255);
                font-weight: bold;
            }

            .dataTableRow {
                background-color: #DADFE0;
            }

            .dataTableRowSelected {
                background-color: rgb(222, 228, 232);
            }

            .dataTableRowOver {
                background-color: #fcf5dd;
                cursor: pointer;
            }

            .dataTableContent {
                font-family: Verdana, Arial, sans-serif;
                font-size: 11px;
                color: rgb(0, 0, 0);
            }

            .dataTableContentRed {
                font-family: Verdana, Arial, sans-serif;
                font-size: 11px;
                color: rgb(204, 0, 0);
            }

            .dataTableContentRedAlert {
                font-family: Verdana, Arial, sans-serif;
                font-size: 11px;
                color: rgb(255, 0, 0);
                font-weight: bold;
            }

            a {
                text-decoration: none;
            }

            a:hover {
                text-decoration: underline;
            }
        </style>

        <div style="width: 100%; font-size: 11px; overflow-x: auto;">
            <table border="0"
                   width="<?= 170 + count($data) * 250; ?>"
                   cellspacing="2" cellpadding="2">
                <tr class="dataTableHeadingRow">
                    <td class="dataTableHeadingContent" align="center"
                        width="170"
                        style="background-color: white;">&nbsp;</td>
                    <?php foreach (array_keys($data) as $rep_name) { ?>
                        <td class="dataTableHeadingContent" align="center"
                            width="250" style="font-size: 12px;">
                            <table width="95%" border="0">
                                <tr>
                                    <?php
                                    if ("No Sales Rep." !== $rep_name) {
                                        ?>
                                        <td style="width:20px;">
                                            <input
                                                style="vertical-align: text-bottom;"
                                                type="checkbox"
                                                name="selector_<?= $data[$rep_name]['rep_id']; ?>"
                                                id="selector_<?= $data[$rep_name]['rep_id']; ?>"
                                                data-rep-id="<?= $data[$rep_name]['rep_id']; ?>"
                                                class="rep-select-all"
                                                title="Select/deselect all">
                                        </td>
                                    <?php } ?>
                                    <td style="text-align: center;">
                                        <?= $rep_name; ?>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    <?php } ?>
                    <td style="background-color: white;">&nbsp;</td>
                </tr>
                <?php
                $_report_start_date = null;
                $_report_end_date = null;
                ?>
                <?php while (1) { ?>
                    <?php
                    $reportDates = $block->getReportDatesRange(
                        $to_date,
                        $from_date,
                        $reportType,
                        $_report_end_date,
                        $_report_start_date
                    );

                    if ($reportDates == false) {
                        break;
                    }
                    $_report_end_date = $reportDates['report_end_date'];
                    $_report_start_date = $reportDates['report_start_date'];
                    $_report_date_label = $reportDates['report_date_label'];
                    ?>
                    <tr class="dataTableRow">
                        <td class="dataTableContent"
                            align="center"><?= $_report_date_label; ?></td>
                        <?php
                        $currency_symbol = $block->getCurrencySymbol();

                        $subtotals = [];

                        foreach ($data as $rep_name => $admin_data):?>
                            <td class="dataTableContent" align="center"
                                valign="top">
                                <table width="95%" border="0">
                                    <?php $_has_orders = false;

                                    foreach ($admin_data['orders'] as $_order) {
                                        $d = strtotime($_order['created_at']);
                                        if (strtotime($_order['created_at']) > $_report_start_date && strtotime($_order['created_at']) < $_report_end_date) {
                                            echo '<tr>';

                                            if ($block->isAllowedForUser('Cminds_Salesrep::change_representative_commission_status') && "No Sales Rep." != $rep_name) {
                                                echo '<td style="width:13px;"><input data-rep-id-child="' . $admin_data['rep_id'] . '" type="checkbox" name="order_ids_' . $admin_data['rep_id'] . '" value="' . $_order['order_id'] . '"></td>';
                                            }

                                            if ($_order['show_status'] && "No Sales Rep." != $rep_name) {
                                                if ($_order['status'] != "") {
                                                    $_salesrep_icon = $block->getViewFileUrl('Cminds_Salesrep::images/salesrep/' . strtolower($_order['status']) . '.png');
                                                } else {
                                                    $_order['status'] = "Unpaid";
                                                    $_salesrep_icon = $block->getViewFileUrl('Cminds_Salesrep::images/salesrep/unpaid.png');
                                                }
                                                echo '<td style="width: 16px;"><img style="margin-top: 2px;" src="' . $_salesrep_icon . '" alt="' . $_order['status'] . ' icon" title="' . $_order['status'] . '" /></td>';
                                            }

                                            if ("No Sales Rep." != $rep_name) {
                                                echo '<td align="left">';
                                            } else {
                                                echo '<td align="center">';
                                            }

                                            echo '<a style="vertical-align: top;" target="_blank" href="' . $block->getUrl('sales/order/view',
                                                    ['order_id' => $_order['order_id']]) . '">';
                                            echo $_order['order_increment_id'];

                                            if ($_order['is_manager']) {
                                                echo ' (M)';
                                            }

                                            echo '</a>';
                                            echo '</td>';

                                            if ("No Sales Rep." !== $rep_name) {
                                                echo '<td align="right">';
                                                echo $_order['value'] != '' ? $block->getCurrency($_order['value']) : '';
                                                echo '</td>';
                                                echo '</tr>';
                                            }

                                            // Calc subtotal earned for period
                                            if ("canceled" != strtolower($_order['order_status'])) {
                                                if (isset($subtotals[$rep_name])) {
                                                    $subtotals[$rep_name]['subtotal'] += round($_order['value'],
                                                        2);
                                                    $subtotals[$rep_name]['orders'] += 1;
                                                } else {
                                                    $subtotals[$rep_name] = [
                                                        'subtotal' => round($_order['value'],
                                                            2),
                                                        'orders' => 1
                                                    ];
                                                }
                                            } else {
                                                if (isset($subtotals[$rep_name])) {
                                                    $subtotals[$rep_name]['subtotal'] += round(0,
                                                        2);
                                                    $subtotals[$rep_name]['orders'] += 1;
                                                } else {
                                                    $subtotals[$rep_name] = [
                                                        'subtotal' => round(0,
                                                            2),
                                                        'orders' => 1
                                                    ];
                                                }
                                            }
                                            $_has_orders = true;
                                        }
                                    }

                                    if (!$_has_orders) {
                                        $subtotals[$rep_name] = [
                                            'subtotal' => 0,
                                            'orders' => 0
                                        ];

                                        echo '<tr><td colspan="2" align="center">-</td></tr>';
                                    } ?>
                                </table>
                            </td>
                        <?php endforeach; ?>
                        <td style="background-color: white;">&nbsp;</td>
                    </tr>
                    <tr class="dataTableRow dataTableRowOver">
                        <td class="dataTableContent">&nbsp;</td>
                        <?php foreach (array_keys($data) as $rep_name) { ?>
                            <td class="dataTableContent" align="center"
                                valign="top">
                                <?php if ("No Sales Rep." != $rep_name) { ?>
                                    <table style="width: 95%;" border="0">
                                        <tr>
                                            <?php
                                            if ($block->isAllowedForUser('Cminds_Salesrep::change_representative_commission_status')) { ?>
                                                <td style="width: 13px;"></td>
                                            <?php } ?>
                                            <td style="width: 16px;"></td>
                                            <td align="left">
                                                <b><?= __('Orders:'); ?></b><?= $subtotals[$rep_name]['orders']; ?>
                                            </td>
                                            <td align="right">
                                                <?php if ($data[$rep_name]['show_comm']) { ?>
                                                    <b><?= __('Subtotal:') ?></b> <?= $subtotals[$rep_name]['subtotal'] == '' ? $block->getCurrency(0) : $block->getCurrency($subtotals[$rep_name]['subtotal']); ?>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                    </table>
                                <?php } ?>
                            </td>
                        <?php } ?>
                        <td style="background-color: white;">&nbsp;</td>
                    </tr>
                <?php }; ?>

                <tr class="dataTableRow dataTableRowOver">
                    <td class="dataTableContent">&nbsp;</td>
                    <?php foreach (array_keys($data) as $rep_name) { ?>
                        <td class="dataTableContent" align="center"
                            valign="top">
                            <?php if ("No Sales Rep." !== $rep_name) { ?>
                                <table style="width: 95%;" border="0">
                                    <tr>
                                        <?php if ($block->isAllowedForUser('Cminds_Salesrep::change_representative_commission_status')) { ?>
                                            <td style="width: 13px;"></td>
                                        <?php } ?>
                                        <td style="width: 16px;"></td>
                                        <td align="left">
                                            <b><?= __('Orders:') ?> </b><?= $subtotals[$rep_name]['orders']; ?>
                                        </td>
                                        <td align="right">
                                            <?php if ($data[$rep_name]['show_comm']) { ?>
                                                <b><?= __('Subtotal:'); ?></b> <?= $subtotals[$rep_name]['subtotal'] == '' ? $block->getCurrency(0) : $block->getCurrency($subtotals[$rep_name]['subtotal']) ?>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                </table>
                            <?php } ?>
                        </td>
                    <?php } ?>
                    <td style="background-color: white;">&nbsp;</td>
                </tr>
                <?php
                if ($block->isAllowedForUser('Cminds_Salesrep::change_representative_commission_status')) { ?>
                    <tr>
                        <td align="center" width="160">&nbsp;</td>
                        <?php foreach (array_keys($data) as $rep_name) { ?>
                            <td align="center" valign="top"
                                style="background-color:#F0F1F1;">
                                <?php
                                if ("No Sales Rep." !== $rep_name) {
                                    ?>
                                    <table style="width: 98%;" border="0">
                                        <tr>
                                            <td style="text-align: left; vertical-align: bottom; font-size: 12px;">
                                                <img style=""
                                                     src="<?= $block->getViewFileUrl('Cminds_Salesrep::images/salesrep/arrow_ltr.png'); ?>"
                                                     alt="Change selected orders."/>
                                                <?= __('change selected to:') ?>
                                            </td>
                                            <td style="text-align: right; vertical-align: bottom;">
                                                <form method="post"
                                                      name="rep-id-status-form-<?= $data[$rep_name]['rep_id']; ?>"
                                                      action="<?= $block->getStatusFormAction() ?>">
                                                    <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>"/>
                                                    <input type="hidden" name="sales_rep_id" value="<?= $data[$rep_name]['rep_id']; ?>"/>

                                                    <select
                                                        style="margin-bottom: 2px;"
                                                        class="rep-status-select"
                                                        data-rep-id-select="<?= $data[$rep_name]['rep_id']; ?>"
                                                        id="status_<?= $data[$rep_name]['rep_id']; ?>"
                                                        name="status">
                                                        <?php $statuses = $block->getStatusList();
                                                        echo '<option value=""></option>';

                                                        foreach ($statuses as $status) {
                                                            $commission_status = $block->getFilterData()->getCommissionStatuses();
                                                            if (isset($commission_status)) {
                                                                if ($block->getFilterData()->getCommissionStatuses() != $status['value']) {
                                                                    echo '<option value="' . $status['value'] . '">' . $status['label'] . '</option>';
                                                                }
                                                            } else {
                                                                echo '<option value="' . $status['value'] . '">' . $status['label'] . '</option>';
                                                            }
                                                        } ?>
                                                    </select>
                                                </form>
                                            </td>
                                        </tr>
                                    </table>
                                <?php } ?>
                            </td>
                        <?php } ?>
                    </tr>
                <?php } ?>
                <tr>
                    <td>&nbsp;</td>
                    <?php foreach (array_keys($data) as $rep_name) { ?>
                        <td class="dataTableContent" align="center"
                            style="width: 250px; background-color:#F0F1F1;">
                            <table
                                style="width: 90%; margin: 10px; font-size: 15px; font-weight: bold;">
                                <?php
                                if ("No Sales Rep." !== $rep_name && $data[$rep_name]['show_comm']) {
                                    ?>
                                    <tr>
                                        <td><?= __('Paid Total:') ?></td>
                                        <td align="right"
                                            style="color: green;"><?= $block->getCurrency($data[$rep_name]['paid_total']); ?></td>
                                    </tr>
                                    <tr>
                                        <td><?= __('Unpaid Total:') ?></td>
                                        <td align="right"
                                            style="color: red;"><?= $block->getCurrency($data[$rep_name]['unpaid_total']); ?></td>
                                    </tr>
                                <?php } ?>
                            </table>
                        </td>
                    <?php } ?>
                </tr>

            </table>
        </div>
        <br/><br/>
        <i><?= __('We strongly recommend paying commissions based on the period in which
            you accept returns. This prevents you from paying commission on an
            order that is later cancelled. For example, if you accept returns
            for 30 days, generate this report at the end of a 30 day period.
            Make sure to diligently mark any canceled or returned orders as
            such.'); ?>
        </i>
        <?php
    else :
        ?>
        <?php
    endif;
    ?>
<?php endif; ?>
