<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Checkout\Block\Onepage\Success */
?>
<?php 

?>
<div class="checkout-success visaCheckout">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>

<script>
 require([
 'Magento_Customer/js/customer-data'
 ], function (customerData) {
     var sections = ['cart'];
     customerData.invalidate(sections);
     customerData.reload(sections, true);
 });
 </script>

<!-- Code for Action: Conversion_-_Toronto_Vaporizers -->

<?php
 $order_hepler=$this->helper('\Ktpl\General\Helper\Ordersuccess');
 $row_total=$order_hepler->getGrandTotal($block->getOrderId()); 
 $total = number_format($row_total,2);

$setArgs = '';
$setArgs=$order_hepler->getArgs(); 

 ?>

<!-- Begin Rocket Fuel Conversion Action Tracking Code Version 9 -->
<script type='text/javascript'>
(function() {
    var w = window, d = document;
    var s = d.createElement('script');
    s.setAttribute('async', 'true');
    s.setAttribute('type', 'text/javascript');
    s.setAttribute('src', '//c1.rfihub.net/js/tc.min.js');
    var f = d.getElementsByTagName('script')[0];
    f.parentNode.insertBefore(s, f);
    if (typeof w['_rfi'] !== 'function') {
        w['_rfi']=function() {
            w['_rfi'].commands = w['_rfi'].commands || [];
            w['_rfi'].commands.push(arguments);
        };
    }
     _rfi('setArgs', 'ver', '9');
     _rfi('setArgs', 'rb', '32982');
     _rfi('setArgs', 'ca', '<?php echo $setArgs; ?>');
     _rfi('setArgs', '_o', '32982');
     _rfi('setArgs', '_t', '<?php echo $setArgs; ?>');
     _rfi('setArgs', 'revenue', '<?php echo $total; ?>');
     _rfi('setArgs', 'transid', '<?php echo $this->getOrderId(); ?>');
     _rfi('track');
})();
</script>
<noscript>
  <iframe src='//<?php echo $setArgs; ?>p.rfihub.com/ca.html?rb=32982&ca=<?php echo $setArgs; ?>&_o=32982&_t=<?php echo $setArgs; ?>&ra=&revenue=<?php echo $total; ?>&transid=<?php echo $block->getOrderId(); ?>' style='display:none;padding:0;margin:0' width='0' height='0'>
</iframe>
</noscript>
<!-- End Rocket Fuel Conversion Action Tracking Code Version 9 -->
 
 <?php 

$helper = $this->helper('\Ktpl\General\Helper\Data');
$currentStoreID = $helper->getCurrentStoreId();
    switch ($currentStoreID) {
        case '2': ?>
                <script type="text/javascript">
                var utag_data = {
                    revenue : "<?php echo $total; ?>",
                    orderid : "<?php echo $this->getOrderId(); ?>"
                    }
                </script>
                <!-- Loading script asynchronously -->
                <script type="text/javascript">
                (function(a,b,c,d){
                    a='//tags.tiqcdn.com/utag/audiencex/torontovaporizer/prod/utag.js';
                    b=document;
                    c='script';
                    d=b.createElement(c);
                    d.src=a;
                    d.type='text/java'+c;
                    d.async=true;
                    a=b.getElementsByTagName(c)[0];
                    a.parentNode.insertBefore(d,a);
                    })();
                </script> <?php
            break;

        case '3': ?>
                <script type="text/javascript">
                    var utag_data = {   
                        revenue : "<?php echo $total; ?>",
                        orderid : "<?php echo $this->getOrderId(); ?>"
                    }
                </script>
                <!-- Loading script asynchronously -->
                <script type="text/javascript">
                    (function(a,b,c,d){
                        a='//tags.tiqcdn.com/utag/audiencex/tvape/prod/utag.js';
                        b=document;
                        c='script';
                        d=b.createElement(c);
                        d.src=a;
                        d.type='text/java'+c;
                        d.async=true;
                        a=b.getElementsByTagName(c)[0];
                        a.parentNode.insertBefore(d,a);
                    })();
                </script> <?php
            break;
    }

?>
