<?php $columnsLimit = $block->getColumnsLimit() ? : 0; ?>
<?php $_menu2 = $block->getHtml('level-top', 'mega', $columnsLimit) ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$ecommerceHelper =$objectManager->get('Magento\Store\Model\StoreManagerInterface');
 $currentStorecode = $ecommerceHelper->getStore()->getCode(); ?>
<?php if ($block->allowExtension()): ?>
    <script>

        require([
            'jquery',
            'ibnabmodernizr'
        ], function ($) {


            $('.menu > ul > li:has( > ul)').addClass('menu-dropdown-icon');
            //Checks if li has sub (ul) and adds class for toggle icon - just an UI


            $('.menu > ul > li > ul:not(:has(ul))').addClass('normal-sub');
            //Checks if drodown menu's li elements have anothere level (ul), if not the dropdown is shown as regular dropdown, not a mega menu (thanks Luka Kladaric)
            <?php if($currentStorecode=='vaporizera_en') { ?>
                $('.normal-sub').addClass('normal-sub2');
            <?php } ?>    
            $(".menu > ul").before("<a href=\"#\" class=\"menu-mobile\">Navigation</a>");

            //Adds menu-mobile class (for mobile toggle menu) before the normal menu
            //Mobile menu is hidden if width is more then 959px, but normal menu is displayed
            //Normal menu is hidden if width is below 959px, and jquery adds mobile menu
            //Done this way so it can be used with wordpress without any trouble

            $(".menu > ul > li").hover(function (e) {
                if ($(window).width() > 943) {
                    $(this).children("ul").stop(true, false).fadeToggle(10);
                    e.preventDefault();
                }
            });
            
            $(".menu > ul > li").one('mouseout',function (e) {
                if ($(window).width() > 943) {
                    e.preventDefault();
                    $(".menu > ul > li > ul").css('display','none');
                    $(this).children("ul").css('display','block');
                }
            });
            //If width is more than 943px dropdowns are displayed on hover
            
            if($(window).width() <= 943) {
                $(".menu > ul > li").on('click',function (e) {
                    if ( !$(e.target).is('img') ) {
                        e.preventDefault();
                        $(".menu > ul > li > ul").css('display','none');
                        $(this).children("ul").css('display','block');
                        // $(".menu-dropdown-icon").removeClass('activemenu');
                        // $(this).find('.menu-dropdown-icon').addClass('activemenu');
                    }
                });
            }

            //If width is less or equal to 943px dropdowns are displayed on click (thanks Aman Jain from stackoverflow)

            $(".menu-mobile").click(function (e) {
                $(".menu > ul").toggleClass('show-on-mobile');
                e.preventDefault();
            });




        });

    </script>
    <?php
    /**
     * Top menu for store
     *
     * @see \Magento\Theme\Block\Html\Topmenu
     */
    ?>
    <nav class="navigation" role="navigation" >

        <div class="menu" id="om">
            <ul>
                <?php /* @escapeNotVerified */ echo $_menu2; ?>
            </ul>
        </div>
        <ul id="dm" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */ echo $_menu; ?>
        </ul>
    </nav>

<?php else : ?>

    <nav class="navigation" role="navigation">
<?php /* @escapeNotVerified */ echo $_menu; ?>
    </nav>
<?php endif; ?>


<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){ 
    if($(window).width() <= 943) {
        $(".switcher.language.switcher-language").on('click',function (e) {
            if ( !$(e.target).is('img#custom-language') && !$(e.target).is('span.lang-code')) { 
                
                    e.preventDefault();
                    
                    $(".ui-dialog.ui-widget.ui-widget-content.ui-corner-all.ui-front.mage-dropdown-dialog:eq(0)").toggle();
                }
                
        });
    }   
});
</script> 