<form id="paysafe_form" action="<?php echo $block->getPaymentResponseUrl(); ?>" method="POST">
    <input id="paysafe_token_change" type="hidden" name="paysafe_token_change"/>
    <input id="amount" type="hidden" name="amount" value=<?php echo $block->getAmount(); ?> />
</form>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-3"></div>
            <div class="col-xs-12 col-md-7">
                <div class="panel-base panel-default credit-card-box">
                    <div class="panel-heading display-table" >
                        <div class="row" >
                            <div class="display-title"><h3 class="panel-title">Payment Details</h3></div>
                            <div class="display-logo">
                                <?php
                                    $cardBrand = explode(",",$block->getBrand());
                                    foreach ($cardBrand as $card) {
                                    ?>
                                        <img  style="height: 30px;" src="<?php echo $block->getViewFileUrl('Paysafe_Paysafe::images/'.strtolower($card).'.png'); ?>">
                                    <?php
                                    }
                                ?>                            
                            </div>
                        </div>                    
                    </div>
                    <div class="panel-body">
                        <form role="form" id="payment-form" method="POST" action="javascript:void(0);">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="cardNumber">CARD NUMBER</label>
                                        <div class="input-group">
                                            <div class="form-control" id="cardNumber"> </div>
                                            <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                                        </div>
                                    </div>                            
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-7 col-md-7">
                                    <div class="form-group">
                                        <label for="cardExpiry"><span class="hidden-xs">EXPIRATION</span><span class="visible-xs-inline">EXP</span> DATE</label>
                                        <div class="form-control" id="cardExpiry"></div>
                                    </div>
                                </div>
                                <div class="col-xs-5 col-md-5 pull-right">
                                    <div class="form-group">
                                        <label for="cardCVC">CV CODE</label>
                                        <div class="form-control" id="cardCVC"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <a href="<?php echo $block->getCancelUrl(); ?>">
                                    <div class="col-xs-6 col-md-6">
                                        <button class="btn btn-cancel btn-lg btn-block" type="button">Cancel</button>
                                    </div>
                                </a>
                                <div class="col-xs-6 col-md-6">
                                    <button class="change btn btn-success btn-lg btn-block" type="button">Change</button>
                                </div>
                            </div>
                            <div class="row" style="display:none;">
                                <div class="col-xs-12">
                                    <p align="center" class="payment-errors"></p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>               
            </div>
            <div class="col-xs-12 col-md-3"></div>            
        </div>
    </div>

<script type = "text/javascript">
    var apiKey = "<?php echo $block->getApiKey(); ?>";
    var paysafeEnvironment = "<?php echo $block->getEnvironment(); ?>";
    var brand = "<?php echo $block->getBrand(); ?>";
    var arrayBrand = brand.split(",");
    var isCardValid;

    $(document).ready(function() {
            var $form = $('#payment-form');
            $form.find('.change').prop('disabled', true);
        
            var options = {
        
                // select the Paysafe test / sandbox environment
                environment: paysafeEnvironment,
        
                // set the CSS selectors to identify the payment field divs above
                // set the placeholder text to display in these fields
                fields: {
                    cardNumber: {
                        selector: "#cardNumber",
                        placeholder: "Card Number"
                    },
                    expiryDate: {
                        selector: "#cardExpiry",
                        placeholder: "MM / YY"
                    },
                    cvv: {
                        selector: "#cardCVC",
                        placeholder: "CVV"
                    }
                }
            };
            
            // initalize the hosted iframes using the SDK setup function
            paysafe.fields.setup(apiKey, options, function(instance, error) {
                if (error) {
                    console.log(error);
                }
                
                var changeButton = $form.find('.change');
        
                instance.fields("cvv cardNumber expiryDate").valid(function (eventInstance, event) {
                    $(event.target.containerElement).closest('.form-control').removeClass('error').addClass('success');
                    if (paymentFormReady()) {
                        $form.find('.change').prop('disabled', false);
                    }
                });
        
                instance.fields("cvv cardNumber expiryDate").invalid(function (eventInstance, event) {
                    $(event.target.containerElement).closest('.form-control').removeClass('success').addClass('error');
                    if (!paymentFormReady()) {
                        $form.find('.change').prop('disabled', true);
                    }
                });
                
                instance.on("CardBrandRecognition", function(instance, event) {
                    if (instance.getCardBrand()) {
                        var cardBrand = instance.getCardBrand().replace(/\s+/g, '');
                        switch (cardBrand) {
                            case "AmericanExpress":
                              $form.find(".fa").removeClass().addClass('fa fa-cc-amex');
                              break;
                            case "MasterCard":
                              $form.find(".fa").removeClass().addClass('fa fa-cc-mastercard');
                              break;
                            case "Visa":
                              $form.find(".fa").removeClass().addClass('fa fa-cc-visa');
                              break;
                            case "Diners":
                              $form.find(".fa").removeClass().addClass('fa fa-cc-diners-club');
                              break;
                            case "JCB":
                              $form.find(".fa").removeClass().addClass('fa fa-cc-jcb');
                              break;
                            case "Maestro":
                              $form.find(".fa").removeClass().addClass('fa fa-cc-discover');
                              break;
                        }
                        if (arrayBrand.indexOf(cardBrand) > -1) {
                            isCardValid = true;
                        } else {
                            isCardValid = false;
                        }
                        
                        if (paymentFormReady()) {
                            $form.find('.change').prop('disabled', !isCardValid);
                        }
                    } else {
                        $form.find(".fa").removeClass().addClass('fa fa-credit-card');
                    }
                });
                instance.fields("cvv cardNumber expiryDate").valid(function (eventInstance, event) {
                    if (paymentFormReady()) {
                        $form.find('.change').prop('disabled', !isCardValid);
                    }
                });
                changeButton.bind("click", function (event) {
                    instance.tokenize(
                        function(instance, error, result) {
                        if (error) {
                            console.log(error);
                            $form.find('.change').html('Try again').prop('disabled', false);
        
                            /* Show Paysafe errors on the form */
                            $form.find('.payment-errors').text(error.detailedMessage);
                            $form.find('.payment-errors').closest('.row').show();
                        } else {
                            /* Visual feedback */
                            $form.find('.change').html('Processing <i class="fa fa-spinner fa-pulse"></i>');
        
                            /* Hide Paysafe errors on the form */
                            $form.find('.payment-errors').closest('.row').hide();
                            $form.find('.payment-errors').text("");
                            // response contains token          
                            console.log("Card tokenization successful, token " + result.token);
                            // AJAX - you would send 'token' to your server here and invoke Authorization agains Paysafe's Card API
                            document.getElementById('paysafe_token_change').value = result.token;
                            document.getElementById('paysafe_form').submit();
                        }
                    });
                });
            });
    });
    
    function paymentFormReady() {
        return $('#cardNumber').hasClass("success") 
                && $('#cardExpiry').hasClass("success") 
                && $('#cardCVC').hasClass("success");
    }
</script>
