
<?php if ($block->getCaptureMethod() == 'PAYSAFEJS') { ?>
<?php if ($block->getIsRecurringActive()): ?>
        <?php if ($block->getCustomerDataCreditCard()): ?>
            <center>
                <h2><?php echo __('Use stored payment data') ?></h2>
            <?php foreach ($block->getCustomerDataCreditCard() as $item) { ?>
                <div class="group-list">
                    <div class="group-img">
                        <img src="<?php echo $block->getViewFileUrl('Paysafe_Paysafe/images').'/'.strtolower($item['brand']).'.png';?>" class="brandImage" alt="<?=$item['brand']?>">
                    </div>
                    <span class="group-info"><?php echo __('ending in').": ".$item['last_digits']."; ".__('expires on').": ".$item['expiry_month']."/".substr($item['expiry_year'],-2);?></span>
                    <div class="group-button">
                        <form action="<?php echo $block->getPaymentResponseUrl() ?>" method="post">
                            <input id="paysafe_token_recurring" type="hidden" name="paysafe_token_recurring" value="<?php echo $item['payment_token']; ?>" />
                            <input id="amount" type="hidden" name="amount" value=<?php echo $block->getAmount(); ?> />
                            <input id="currency_code" type="hidden" name="currency_code" value=<?php echo $block->getCurrencyCode(); ?> />
                            <input id="recurring" type="hidden" name="recurring" value="RECURRING" />
                            <button class="action primary btnChange" type="submit" value="submit"><?php echo __('Pay Now') ?></button>
                        </form>
                    </div>
                    <div style="clear:both"></div>
                </div>
            <?php } ?>
            <h2><?php echo __('Use alternative payment data') ?></h2>
            </center>
        <?php endif; ?>
<?php endif; ?>
<?php } ?>
<form id="paysafe_form" action="<?php echo $block->getPaymentResponseUrl(); ?>" method="POST">
    <input id="paysafe_token" type="hidden" name="paysafe_token"/>
    <input id="amount" type="hidden" name="amount" value=<?php echo $block->getAmount(); ?> />
    <input id="currency_code" type="hidden" name="currency_code" value=<?php echo $block->getCurrencyCode(); ?> />
    <input id="recurring" type="hidden" name="recurring" value="INITIAL" />
</form>
<div id="overlay" onclick="on()">
  <div id="overlay-image">
      <img src="<?php echo $block->getViewFileUrl('Paysafe_Paysafe::images/loader.gif'); ?>">
  </div>
</div>
 <button id="paysafe_checkout" style="display: none;" onclick="paysafeCheckout()">Pay</button>
<?php
    if ($block->getCaptureMethod() == 'PAYSAFEJS') {
        ?>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="panel-base panel-default credit-card-box">
                    <div class="panel-heading display-table" >
                        <div class="row" >
                            <div class="display-title"><h3 class="panel-title">Payment Details</h3></div>
                            <div class="display-logo">
                                <?php
                                    $cardBrand = explode(",",$block->getBrand());
                                    foreach ($cardBrand as $card) {
                                    ?>
                                        <img  style="height: 30px;" src="<?php echo $block->getViewFileUrl('Paysafe_Paysafe::images/'.strtolower($card).'.png'); ?>">
                                    <?php
                                    }
                                ?>                            
                            </div>
                        </div>                    
                    </div>
                    <div class="panel-body">
                        <form role="form" id="payment-form" method="POST" action="javascript:void(0);">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="cardNumber">CARD NUMBER</label>
                                        <div class="input-group">
                                            <div class="form-control" id="cardNumber"> </div>
                                            <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                                        </div>
                                    </div>                            
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-7 col-md-7">
                                    <div class="form-group">
                                        <label for="cardExpiry"><span class="hidden-xs">EXPIRATION</span><span class="visible-xs-inline">EXP</span> DATE</label>
                                        <div class="form-control" id="cardExpiry"></div>
                                    </div>
                                </div>
                                <div class="col-xs-5 col-md-5 pull-right">
                                    <div class="form-group">
                                        <label for="cardCVC">CV CODE</label>
                                        <div class="form-control" id="cardCVC"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <button class="payNow btn btn-success btn-lg btn-block" type="button">Pay Now</button>
                                </div>
                            </div>
                            <div class="row" style="display:none;">
                                <div class="col-xs-12">
                                    <p align="center" class="payment-errors"></p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>               
            </div>         
        </div>
    </div>
    <?php
    }
?>
<script type="text/javascript" language="javascript">
    require(
        [
            "jqueryNoConflict",
            "paysafe",
            "paysafe.checkout"
        ],
        function(jQuery)
    {
        (function ($)
        {
            var apiKey = "<?php echo $block->getApiKey(); ?>";
            var paysafeEnvironment = "<?php echo $block->getEnvironment(); ?>";
            var captureMethod = "<?php echo $block->getCaptureMethod(); ?>";
            var brand = "<?php echo $block->getBrand(); ?>";
            var arrayBrand = brand.split(",");
            var isCardValid;

            $(document).ready(function() {
                if (captureMethod ==  'PAYSAFEJS') {
                    var $form = $('#payment-form');
                    $form.find('.payNow').prop('disabled', true);
                
                    var options = {
                
                        // select the Paysafe test / sandbox environment
                        environment: paysafeEnvironment,
                
                        // set the CSS selectors to identify the payment field divs above
                        // set the placeholder text to display in these fields
                        fields: {
                            cardNumber: {
                                selector: "#cardNumber",
                                placeholder: "Card Number"
                            },
                            expiryDate: {
                                selector: "#cardExpiry",
                                placeholder: "MM / YY"
                            },
                            cvv: {
                                selector: "#cardCVC",
                                placeholder: "CVV"
                            }
                        }
                    };
                    
                    // initalize the hosted iframes using the SDK setup function
                    paysafe.fields.setup(apiKey, options, function(instance, error) {
                        if (error) {
                            console.log(error);
                        }
                        
                        var payNowButton = $form.find('.payNow');
                
                        instance.fields("cvv cardNumber expiryDate").valid(function (eventInstance, event) {
                            $(event.target.containerElement).closest('.form-control').removeClass('error').addClass('success');
                            if (paymentFormReady()) {
                                $form.find('.payNow').prop('disabled', false);
                            }
                        });
                
                        instance.fields("cvv cardNumber expiryDate").invalid(function (eventInstance, event) {
                            $(event.target.containerElement).closest('.form-control').removeClass('success').addClass('error');
                            if (!paymentFormReady()) {
                                $form.find('.payNow').prop('disabled', true);
                            }
                        });
                        
                        instance.on("CardBrandRecognition", function(instance, event) {
                            if (instance.getCardBrand()) {
                                var cardBrand = instance.getCardBrand().replace(/\s+/g, '');
                                switch (cardBrand) {
                                    case "AmericanExpress":
                                      $form.find(".fa").removeClass().addClass('fa fa-cc-amex');
                                      break;
                                    case "MasterCard":
                                      $form.find(".fa").removeClass().addClass('fa fa-cc-mastercard');
                                      break;
                                    case "Visa":
                                      $form.find(".fa").removeClass().addClass('fa fa-cc-visa');
                                      break;
                                    case "Diners":
                                      $form.find(".fa").removeClass().addClass('fa fa-cc-diners-club');
                                      break;
                                    case "JCB":
                                      $form.find(".fa").removeClass().addClass('fa fa-cc-jcb');
                                      break;
                                    case "Maestro":
                                      $form.find(".fa").removeClass().addClass('fa fa-cc-discover');
                                      break;
                                }
                                if (arrayBrand.indexOf(cardBrand) > -1) {
                                    isCardValid = true;
                                } else {
                                    isCardValid = false;
                                }
                                
                                if (paymentFormReady()) {
                                    $form.find('.payNow').prop('disabled', !isCardValid);
                                }
                            } else {
                                $form.find(".fa").removeClass().addClass('fa fa-credit-card');
                            }
                        });
                        instance.fields("cvv cardNumber expiryDate").valid(function (eventInstance, event) {
                            if (paymentFormReady()) {
                                $form.find('.payNow').prop('disabled', !isCardValid);
                            }
                        });
                        payNowButton.bind("click", function (event) {
                            instance.tokenize(
                                function(instance, error, result) {
                                if (error) {
                                    console.log(error);
                                    $form.find('.payNow').html('Try again').prop('disabled', false);
                
                                    /* Show Paysafe errors on the form */
                                    $form.find('.payment-errors').text(error.detailedMessage);
                                    $form.find('.payment-errors').closest('.row').show();
                                } else {
                                    /* Visual feedback */
                                    $form.find('.payNow').html('Processing <i class="fa fa-spinner fa-pulse"></i>');
                
                                    /* Hide Paysafe errors on the form */
                                    $form.find('.payment-errors').closest('.row').hide();
                                    $form.find('.payment-errors').text("");
                                    // response contains token          
                                    console.log("Card tokenization successful, token " + result.token);
                                    // AJAX - you would send 'token' to your server here and invoke Authorization agains Paysafe's Card API
                                    document.getElementById('paysafe_token').value = result.token;
                                    document.getElementById('paysafe_form').submit();
                                }
                            });
                        });
                    });
                } else {
                    $('#paysafe_checkout').click();
                }
            });
            
            function paymentFormReady() {
                return $('#cardNumber').hasClass("success") 
                        && $('#cardExpiry').hasClass("success") 
                        && $('#cardCVC').hasClass("success");
            }

            function paysafeCheckout() {
                document.getElementById("overlay").style.display = "block";
                paysafe.checkout.setup(apiKey, {
                    amount: <?php echo $block->getAmount(); ?>,
                    currency: "<?php echo $block->getCurrencyCode(); ?>",
                    environment: paysafeEnvironment,
                    companyName: "<?php echo $block->getMerchantName(); ?>"
                }, function(instance, error, result) {
                    if (result.token) {
                        console.log(result.token);
                        document.getElementById('paysafe_token').value = result.token;
                        document.getElementById('paysafe_form').submit();
                    } else {
                        console.log(error);
                        alert(error.detailedMessage);
                    }
                }, function(stage) {
                        if (stage === "BeforePayment" || stage === "DuringPayment") {
                            console.log("Widget is closed");
                            window.location = "<?php echo $block->getCancelUrl(); ?>";
                        }
                    }
                );
            }
        })(jQuery);
    });
</script>
