<?php

class FFDX_ShippingBox_Model_Source_Event_Code extends Mage_Core_Model_Abstract
{
    protected $map = array(
    '1' => 'Delivered', //here was 'Proof of Delivery' - Michael wants 'Delivered'
    '2' => 'Shipment Collected',
    '3' => 'Uplift',
    '4' => 'Arrived Hub',
    '8' => 'Held in Customs - No Paperwork',
    '9' => 'Held in Customs - Inaccurate',
    '10' => 'Awaiting Customs Clearance',
    '15' => 'Out for Delivery',
    '16' => 'Not Delivered - Inaccurate/Incomplete Address',
    '17' => 'Not Delivered - Adverse Weather',
    '18' => 'Not Delivered - Noone available/home',
    '19' => 'Held in Branch',
    '22' => 'Shipper Contacted',
    '23' => 'Bagged',
    '37' => 'Released from Customs',
    '38' => 'Attempted Delivery - Rescheduled Delivery',
    '39' => 'Attempted Delivery - Rejected',
    '40' => 'Arrival Scan',
    '43' => 'Attempted Delivery - Unlocated Consignee',
    '44' => 'Delivery Attempted - Consignee Moved',
    '45' => 'Shipment Returned to Origin/Shipper',
    '50' => 'Hold for Collection',
    '52' => 'Under Clearance',
    '53' => 'Not Delivered - Other Reasons',
    '55' => 'Held in Customs - Other Reasons',
    '61' => 'Held in Branch - Awaiting Customer Advice',
    '66' => 'Shipment Details Created',
    '68' => 'Held in Customs - No Paperwork',
    '69' => 'Driver Despatched For Collection',
    '70' => 'Collection Attempt - Shipment Not Ready',
    '71' => 'Shipment Cancelled',
    '72' => 'Not Delivered - Out of Delivery Area',
    '73' => 'Held in Branch - No Service Area/ODA',
    '74' => 'Attempt to Contact Consignee Failed',
    '75' => 'Collection Scheduled',
    '82' => 'Attemped Delivery',
    '83' => 'Wrong Number',
    '90' => 'Documentation Prepared',
    '91' => 'Booking Arranged',
    '97' => 'Attempted Delivery - Consignee Not Available',
    '98' => 'Attempted Delivery - Consignee Not Available',
    '99' => 'Attempted Delivery - Closed On Arrival',
    '100' => 'Attempted Delivery - Rescheduled Delivery',
    '101' => 'Held in Branch - Arrived Late',
    '102' => 'Attempted Delivery - Rescheduled Delivery',
    '103' => 'Attempted Delivery - Rescheduled Delivery',
    '104' => 'Attempted Delivery - Closed / Holiday',
    '105' => 'Attempted Delivery - Closed / School Holiday',
    '106' => 'Attempted Delivery - Rescheduled by Customer',
    '107' => 'Attempted Delivery - Rescheduled Delivery',
    '155' => 'With Courier for Return',
    '156' => 'Returned to Merchant',
    '157' => 'Attempted Delivery - Out of Country',
    '158' => 'No Answer',
    '247' => 'Incomplete Info/Data',
    '250' => 'Held in Branch - Rescheduled by Customer',
    '251' => 'Rejected',
    '256' => 'Held in Branch - Appointment Booked',
    '257' => 'Shipment Forwarded to Customer Service',
    '258' => 'Documents Not Ready',
    '262' => 'Ready for Routing',
    '263' => 'Held in Branch to be Returned',
    '264' => 'Confirmed',
    '265' => 'Shipment Forwarded to Operations',
    '267' => 'Ready for Return Service',
    '275' => 'Attemped Delivery - Mobile Switched Off',
    '276' => 'Mobile Switched Off',
    '277' => 'Attempted Delivery - Wrong Number',
    '301' => 'Unable to Attempt',
    '310' => 'Confirmed – ODA Zone A',
    '311' => 'Confirmed – ODA Zone B',
    '312' => 'Confirmed – ODA Zone C',
    '335' => 'CS update',
);

    
    protected $_event_map = array(
      "@EMBASSY" => "AT Embassy",
      "AS" => "Arrived at Postaplus Location",
      "DELIVERED" => "Delivered to Customer",
      "DESTROYED" => "Destroyed",
      "DISPATCH" => "Dispatched",
      "DR" => "Destination Received",
      "FWD@CAI" => "Forward to Cairo",
      "HD@CUS" => "Held in Customs",
      "HD@TRN" => "Held in Transit",
      "HO" => "Held @ Origin",
      "INVD" => "Shipment Invoiced",
      "INVDEL" => "Invoice Deleted",
      "LA" => "Late Arrival",
      "NEW" => "New Shipment Created",
      "NR" => "No Route",
      "OH" => "On Hold",
      "OS" => "Shipped to Destination",
      "PR" => "Proceed for Route",
      "PU" => "Shipment Picked Up",
      "RAD" => "Shipment received at destination",
      "RC" => "Release Customs",
      "RCS" => "Received From CS",
      "SHTRN" => "Shipment in Transit",
      "TC" => "To Call",
      "TSC" => "The Student Center",
      "TSCRTN" => "Return from The Student Center",
      "UNCLR" => "Under Clearance",
      "VOID" => "Shipment Void",
      "WC" => "Out with Courier",
      "@FWD" => "FORWARDED",
      "@SMSA" => "AT SMSA FACILITY",
      "SDO" => "SHIPMENT DEPARTED FROM ORIGIN",
      "AHF" => "ARRIVED HUB FACILITY",
      "DHF" => "DEPARTED HUB FACILITY",
      "PROHIBIT" => "Prohibited Item",
      "AB" => "Abandon",
      "BA" => "Bad Address",
      "CASH-NA" => "Cash Not Available",
      "CC" => "Company Closed",
      "CL" => "Change Location",
      "CM" => "Company Moved",
      "CNM" => "Civil ID Not Matching",
      "CONFISCATED" => "Confisticated by Customs",
      "CUSCLRD" => "Customs Cleared",
      "DC" => "Deceased",
      "DCR" => "Delay in Clearance",
      "ICL" => "Incomplete Address",
      "MANIFESTED" => "Manifested",
      "MC" => "Missed Commitment",
      "MR" => "Miss Route",
      "NA" => "Not Available",
      "NFL" => "Not Found Location",
      "NT" => "No Time",
      "OB" => "Obtained",
      "OC" => "Out of Country",
      "OS" => "Origin Shipped",
      "PL" => "Person Left",
      "RS" => "Refused Shipment",
      "SD" => "Stop Delivery",
      "UC" => "Under Construction",
      "UNP" => "Unkown Person",
      "FD" => "FUTURE DELIVERY SCHEDULED",
      "NEC" => "Arrived NEC facility",
      "HD@CUSDOC" => "Held in customs- Pending Documents",
      "HD@CUSPRB" => "Held in customs- problem",
      "HD@MINAPR" => "Held for Ministry approval",
      "CLR" => "Cleared",
      "SL" => "Shortly Landed",
      "SHTP" => "Shipment Handover To Third Party",
      "SHDM" => "Shipment Damaged",
      "SKCRS" => "Shipment Not Delivered/Return To Shipper",
      "RFCUSCHG" => "Consignee Refused To Pay Customs Charges",
      "NSA" => "NO SERVICE AREA",
      "CDR" => "CONSIGNEE DOCUMENT REQUIRED",
      "XDR" => "WRONG MOBILE/ WRONG INFORMATION",
      "SHINFRCVD" => "Shipment Information Received",
      "OH@RTO" => "On Hold for RTO",
      "OH@COLLECT" => "On Hold for Collection",
      "OH@ODA" => "On Hold for ODA",
      "OH@CONS" => "On Hold for Consolidation",
      "SH001" => "Received at Operations Facility",
      "SH012" => "Picked Up From Shipper",
      "SH014" => "Record created",
      "SH022" => "Departed Operations facility – In Transit",
      "SH047" => "Received at Origin Facility",
      "SH156" => "Customs Clearance - In Progress",
      "SH249" => "Consignee contacted to set delivery Address And Schedule -SMS Sent",
    ); 
    
    public function toOptionArray()
    {
        return $this
            ->_toOptionArray('value', 'label');
    }

    public function getMap()
    {
        return $this->map;
    }
    
    public function getNewMap(){
        return $this->_event_map;
    }

}